project_id = "sccjdbclijlfivuykyei"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://nolostdocs.rmoddel.com"
additional_redirect_urls = [
  "http://localhost:3001/auth/callback",
  "http://127.0.0.1:3001/auth/callback",
  "https://nolostdocs.rmoddel.com/auth/callback",
  "https://**.amplifyapp.com/auth/callback"
]
jwt_expiry = 3600
